---
title: "In-class Exercise 1 Building Elegant Graphics with ggplot"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
```

# Installing and loading the required libraries

```{r}
packages = c('tidyverse', 'ggrepel')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```
# Import data into R

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

# My first data visualization created using ggplot

```{r}
ggplot(data = exam_data, 
       aes(x = MATHS)) +
  geom_histogram(bins = 20,
                 color = "black",
                 fill = "light blue")
```

##

```{r}
ggplot(data = exam_data, 
       aes(x = MATHS,
            fill = GENDER)) +
  geom_histogram(bins = 20,
                 color = "grey30")
```
